#!/usr/bin/env bash
# Usage:
#   bash scripts/zh_cn/build_zh.sh
#
# Build the Simplified Chinese futurecoder course data.
#
# Details:
#   futurecoder translations may contain placeholders such as `__code0__`.
#   Resolving those placeholders requires `translations/codes.json`, which is
#   generated by `python -m translations.generate_po_file`.
#
#   The generated `translations/english.po` is also the authoritative catalog of
#   translation keys for the current source tree. Before compiling Chinese, this
#   script synchronizes the Chinese PO file with that catalog. Newly added source
#   keys are inserted as clearly marked English fallbacks and written to
#   `translations/zh_missing_report.txt` for later translation.
#
# Prerequisites:
#   - Python 3.12.1
#   - Poetry with project dependencies installed (`poetry install`)
#   - Node.js/npm dependencies installed separately under `frontend/`

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENGLISH_PO="$ROOT_DIR/translations/english.po"
PO_FILE="$ROOT_DIR/translations/locales/zh/LC_MESSAGES/futurecoder.po"
MO_FILE="$ROOT_DIR/translations/locales/zh/LC_MESSAGES/futurecoder.mo"
CODES_FILE="$ROOT_DIR/translations/codes.json"
MISSING_REPORT="$ROOT_DIR/translations/zh_missing_report.txt"

cd "$ROOT_DIR"

if ! command -v poetry >/dev/null 2>&1; then
  echo "ERROR: poetry is not installed or not available in PATH." >&2
  exit 1
fi

if [[ ! -f "$PO_FILE" ]]; then
  echo "ERROR: Chinese PO file not found: $PO_FILE" >&2
  exit 1
fi

echo "[1/5] Generating upstream translation metadata and current source catalog..."
poetry run python -m translations.generate_po_file

if [[ ! -f "$CODES_FILE" ]]; then
  echo "ERROR: translation metadata generation did not produce: $CODES_FILE" >&2
  exit 1
fi

if [[ ! -s "$ENGLISH_PO" ]]; then
  echo "ERROR: source catalog generation did not produce a non-empty file: $ENGLISH_PO" >&2
  exit 1
fi

echo "[2/5] Synchronizing the Chinese catalog with the current source catalog..."
poetry run python scripts/zh_cn/sync_zh_catalog.py \
  "$ENGLISH_PO" \
  "$PO_FILE" \
  --fill-missing-with-source \
  --report "$MISSING_REPORT"

echo "[3/5] Checking Chinese translations and compiling futurecoder.mo..."
poetry run python scripts/zh_cn/check_po_placeholders.py "$PO_FILE" --compile

if [[ ! -f "$MO_FILE" ]]; then
  echo "ERROR: MO compilation did not produce: $MO_FILE" >&2
  exit 1
fi

echo "[4/5] Generating Chinese frontend course data..."
FIX_CORE_IMPORTS=1 \
FUTURECODER_LANGUAGE=zh \
poetry run python -m scripts.generate_static_files

echo "[5/5] Chinese build completed."
echo
if [[ -s "$MISSING_REPORT" ]]; then
  echo "Translation sync report:"
  echo "  $MISSING_REPORT"
  echo "Entries marked AUTO-FALLBACK are temporarily displayed in English."
  echo
fi
echo "Next commands:"
echo "  cd frontend"
echo "  npm ci                 # only needed for first install or lockfile changes"
echo "  npm start"
echo
echo "Then open: http://localhost:3000/course/"
