#!/usr/bin/env bash
# Usage:
#   bash scripts/zh_cn/build_zh.sh
#
# Build the Simplified Chinese futurecoder course data.
#
# Details:
#   futurecoder translations may contain placeholders such as `__code0__`.
#   Resolving those placeholders requires `translations/codes.json`, which is
#   generated by `python -m translations.generate_po_file`. The upstream
#   `scripts/generate.sh` runs that step before generating static frontend data,
#   so this Chinese build script must preserve the same ordering.
#
# Prerequisites:
#   - Python 3.12.1
#   - Poetry with project dependencies installed (`poetry install`)
#   - Node.js/npm dependencies installed separately under `frontend/`

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PO_FILE="$ROOT_DIR/translations/locales/zh/LC_MESSAGES/futurecoder.po"
MO_FILE="$ROOT_DIR/translations/locales/zh/LC_MESSAGES/futurecoder.mo"
CODES_FILE="$ROOT_DIR/translations/codes.json"

cd "$ROOT_DIR"

if ! command -v poetry >/dev/null 2>&1; then
  echo "ERROR: poetry is not installed or not available in PATH." >&2
  exit 1
fi

if [[ ! -f "$PO_FILE" ]]; then
  echo "ERROR: Chinese PO file not found: $PO_FILE" >&2
  exit 1
fi

echo "[1/4] Generating upstream translation metadata..."
poetry run python -m translations.generate_po_file

if [[ ! -f "$CODES_FILE" ]]; then
  echo "ERROR: translation metadata generation did not produce: $CODES_FILE" >&2
  exit 1
fi

echo "[2/4] Checking Chinese translations and compiling futurecoder.mo..."
poetry run python scripts/zh_cn/check_po_placeholders.py "$PO_FILE" --compile

if [[ ! -f "$MO_FILE" ]]; then
  echo "ERROR: MO compilation did not produce: $MO_FILE" >&2
  exit 1
fi

echo "[3/4] Generating Chinese frontend course data..."
FIX_CORE_IMPORTS=1 \
FUTURECODER_LANGUAGE=zh \
poetry run python -m scripts.generate_static_files

echo "[4/4] Chinese build completed."
echo
echo "Next commands:"
echo "  cd frontend"
echo "  npm ci                 # only needed for first install or lockfile changes"
echo "  npm start"
echo
echo "Then open: http://localhost:3000/course/"
